# Clase microsimulación espacial

## Librerías

In [2]:
! pip install pyreadr

import geopandas as gpd
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
import pyreadr

Collecting pyreadr
  Downloading pyreadr-0.5.6-cp313-cp313-win_amd64.whl.metadata (1.4 kB)
Requirement already satisfied: pandas>=1.2.0 in C:\Users\DIGEA\anaconda3\envs\idg\Lib\site-packages (from pyreadr) (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\DIGEA\anaconda3\envs\idg\Lib\site-packages (from pandas>=1.2.0->pyreadr) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\DIGEA\anaconda3\envs\idg\Lib\site-packages (from pandas>=1.2.0->pyreadr) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\DIGEA\anaconda3\envs\idg\Lib\site-packages (from pandas>=1.2.0->pyreadr) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\DIGEA\anaconda3\envs\idg\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadr) (1.17.0)
Downloading pyreadr-0.5.6-cp313-cp313-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ------------- -------------------------- 0.8/2.4 MB 434.9 kB/s eta 0:00:04
   ---------------------- ----------------- 1.3/2.4 MB 756.9 kB/s eta 0:00:02
   ---------------------- ----------------- 1.3/2.4 MB 756.9 kB/s eta 0:00:02
   ------------------------------- -------- 1.8/2.4 MB 867.1 kB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.4 MB 867.1 kB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.4 MB 867.1 kB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 859.6 kB/s  0:00:02
Installing collected packages: pyreadr
Successfully installed pyreadr-0.5.6

# Ejemplo clase 1 microsimulación

In [6]:
RUTA_CENSO_ZONAL = "../DATA/CENSO24/parquet/Cartografía_censo2024_R13_Zonal.parquet"

## Entradas

In [7]:
censo_zonal = gpd.read_parquet(RUTA_CENSO_ZONAL)

In [8]:
censo_zonal

,OBJECTID,CUT,COD_REGION,REGION,COD_PROVINCIA,PROVINCIA,COMUNA,AREA_C,DISTRITO,COD_DISTRITO,...,n_fuente_elect_otro,n_fuente_elect_no_tiene,n_basura_servicios,n_basura_entierra,n_basura_eriazo,n_basura_rio,n_basura_otro,SHAPE_Length,SHAPE_Area,SHAPE
0,2663,13402,13,METROPOLITANA DE SANTIAGO,134,MAIPO,BUIN,URBANO,EL RECURSO,6,...,4.0,1.0,704.0,3.0,0.0,0.0,4.0,0.085226,0.000076,"MULTIPOLYGON (((-70.66374 -33.66766, -70.66357..."
1,2664,13402,13,METROPOLITANA DE SANTIAGO,134,MAIPO,BUIN,URBANO,ALTO JAHUEL,2,...,1.0,0.0,895.0,0.0,1.0,0.0,2.0,0.083812,0.000099,"MULTIPOLYGON (((-70.68434 -33.73325, -70.68432..."
2,2665,13402,13,METROPOLITANA DE SANTIAGO,134,MAIPO,BUIN,URBANO,VALDIVIA DE PAINE,5,...,6.0,4.0,1338.0,2.0,1.0,0.0,1.0,0.176524,0.000170,"MULTIPOLYGON (((-70.79271 -33.77484, -70.79476..."
3,2666,13402,13,METROPOLITANA DE SANTIAGO,134,MAIPO,BUIN,URBANO,VALDIVIA DE PAINE,5,...,10.0,5.0,811.0,0.0,0.0,0.0,1.0,0.063728,0.000153,"MULTIPOLYGON (((-70.85249 -33.80397, -70.85273..."
4,2667,13402,13,METROPOLITANA DE SANTIAGO,134,MAIPO,BUIN,URBANO,BUIN,1,...,0.0,1.0,1865.0,1.0,0.0,0.0,1.0,0.048323,0.000072,"MULTIPOLYGON (((-70.74602 -33.70887, -70.74605..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1860,4524,13504,13,METROPOLITANA DE SANTIAGO,135,MELIPILLA,MARÍA PINTO,URBANO,IBACACHE,4,...,0.0,2.0,350.0,3.0,0.0,0.0,0.0,0.114486,0.000096,"MULTIPOLYGON (((-71.26417 -33.48377, -71.26402..."
1861,4525,13504,13,METROPOLITANA DE SANTIAGO,135,MELIPILLA,MARÍA PINTO,URBANO,LO OVALLE,2,...,0.0,0.0,310.0,0.0,0.0,0.0,0.0,0.030209,0.000033,"MULTIPOLYGON (((-71.08214 -33.46069, -71.08214..."
1862,4526,13118,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,MACUL,URBANO,CAMINO AGRÍCOLA,4,...,0.0,1.0,1023.0,0.0,0.0,0.0,0.0,0.052187,0.000065,"MULTIPOLYGON (((-70.61641 -33.48493, -70.61661..."
1863,4902,13120,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,ÑUÑOA,URBANO,ESTADIO NACIONAL,8,...,1.0,1.0,837.0,0.0,0.0,0.0,0.0,0.053861,0.000098,"MULTIPOLYGON (((-70.60672 -33.46546, -70.60664..."
1864,4909,13120,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,ÑUÑOA,URBANO,PLAZA ZAÑARTU,7,...,0.0,0.0,1263.0,1.0,0.0,0.0,1.0,0.027436,0.000019,"MULTIPOLYGON (((-70.59859 -33.46908, -70.59859..."

# Ejemplo clase 2 microsimulación

In [11]:
ruta_censo_zonal = "../DATA/CENSO24/parquet/Cartografía_censo2024_R13_Zonal.parquet"
ruta_casen = "../DATA/CASEN24/casen_rm.rds"

In [12]:
censo_zonal = gpd.read_parquet(ruta_censo_zonal)
casen_raw = pyreadr.read_r(ruta_casen)

In [13]:
casen_raw = casen_raw[list(casen_raw.keys())[0]]

In [14]:
casen_raw

,id_vivienda,folio,id_persona,region,area,cod_upm,nse,estrato,hogar,expr,...,men18c,may60c,tipohogar,tot_hog,ind_hacina,indsan,ten_viv,ten_viv_f,allega_ext,allega_int
0,1001701.0,100170101.0,1.0,13.0,1.0,10017.0,2.0,1311112.0,1.0,234.0,...,0.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
1,1001701.0,100170101.0,2.0,13.0,1.0,10017.0,2.0,1311112.0,1.0,234.0,...,0.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
2,1001701.0,100170101.0,3.0,13.0,1.0,10017.0,2.0,1311112.0,1.0,234.0,...,0.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
3,1001701.0,100170101.0,4.0,13.0,1.0,10017.0,2.0,1311112.0,1.0,234.0,...,0.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
4,1001701.0,100170101.0,5.0,13.0,1.0,10017.0,2.0,1311112.0,1.0,234.0,...,0.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38669,4584903.0,458490301.0,9.0,13.0,1.0,45849.0,3.0,1311513.0,1.0,158.0,...,1.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
38670,4584907.0,458490701.0,1.0,13.0,1.0,45849.0,3.0,1311513.0,1.0,227.0,...,1.0,0.0,3.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0
38671,4584907.0,458490701.0,2.0,13.0,1.0,45849.0,3.0,1311513.0,1.0,227.0,...,1.0,0.0,3.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0
38672,4584907.0,458490701.0,3.0,13.0,1.0,45849.0,3.0,1311513.0,1.0,227.0,...,1.0,0.0,3.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0
38673,4584907.0,458490701.0,4.0,13.0,1.0,45849.0,3.0,1311513.0,1.0,226.0,...,1.0,0.0,3.0,1.0,1.0,1.0,3.0,2.0,0.0,0.0

## Pre-procesamiento

Se acota el área del censo únicamente a las zonas censales del Gran Stgo

In [20]:
es_gs = (censo_zonal["PROVINCIA"] == 'SANTIAGO') | (
    censo_zonal["COMUNA"].isin(['SAN BERNARDO', 'PUENTE ALTO', 'PIRQUE', 'PADRE HURTADO'])
)

# SE FILTRA EL DF EN BASE A LA CONDICIÓN
censo_zonal = censo_zonal[es_gs].reset_index(drop=True)

In [21]:
censo_zonal

,OBJECTID,CUT,COD_REGION,REGION,COD_PROVINCIA,PROVINCIA,COMUNA,AREA_C,DISTRITO,COD_DISTRITO,...,n_fuente_elect_otro,n_fuente_elect_no_tiene,n_basura_servicios,n_basura_entierra,n_basura_eriazo,n_basura_rio,n_basura_otro,SHAPE_Length,SHAPE_Area,SHAPE
0,2702,13107,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,HUECHURABA,URBANO,HUECHURABA,1,...,1.0,0.0,1397.0,1.0,1.0,0.0,0.0,0.055128,0.000085,"MULTIPOLYGON (((-70.67945 -33.34606, -70.67954..."
1,2703,13107,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,HUECHURABA,URBANO,HUECHURABA,1,...,1.0,0.0,1890.0,2.0,0.0,2.0,2.0,0.098319,0.000228,"MULTIPOLYGON (((-70.66177 -33.35015, -70.66179..."
2,2704,13107,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,HUECHURABA,URBANO,HUECHURABA,1,...,0.0,1.0,1535.0,3.0,2.0,0.0,0.0,0.032909,0.000052,"MULTIPOLYGON (((-70.684 -33.35198, -70.68411 -..."
3,2705,13107,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,HUECHURABA,URBANO,HUECHURABA,1,...,0.0,1.0,2167.0,0.0,0.0,0.0,5.0,0.060684,0.000139,"MULTIPOLYGON (((-70.6639 -33.35881, -70.6639 -..."
4,2706,13107,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,HUECHURABA,URBANO,HUECHURABA,1,...,1.0,2.0,1861.0,1.0,1.0,0.0,1.0,0.059381,0.000141,"MULTIPOLYGON (((-70.67542 -33.35296, -70.67568..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1637,4487,13123,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,PROVIDENCIA,URBANO,PEDRO DE VALDIVIA,2,...,0.0,0.0,1434.0,0.0,0.0,1.0,0.0,0.014824,0.000013,"MULTIPOLYGON (((-70.60952 -33.44183, -70.60948..."
1638,4488,13123,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,PROVIDENCIA,URBANO,HOSPITAL MILITAR,8,...,0.0,0.0,814.0,1.0,0.0,0.0,0.0,0.015632,0.000013,"MULTIPOLYGON (((-70.62259 -33.43018, -70.62235..."
1639,4526,13118,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,MACUL,URBANO,CAMINO AGRÍCOLA,4,...,0.0,1.0,1023.0,0.0,0.0,0.0,0.0,0.052187,0.000065,"MULTIPOLYGON (((-70.61641 -33.48493, -70.61661..."
1640,4902,13120,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,ÑUÑOA,URBANO,ESTADIO NACIONAL,8,...,1.0,1.0,837.0,0.0,0.0,0.0,0.0,0.053861,0.000098,"MULTIPOLYGON (((-70.60672 -33.46546, -70.60664..."
1641,4909,13120,13,METROPOLITANA DE SANTIAGO,131,SANTIAGO,ÑUÑOA,URBANO,PLAZA ZAÑARTU,7,...,0.0,0.0,1263.0,1.0,0.0,0.0,1.0,0.027436,0.000019,"MULTIPOLYGON (((-70.59859 -33.46908, -70.59859..."

Se extraen las variables de la CASEN que se van a utilizar

In [26]:
# en cierto sentido, las vars_fijas son las que explican a la variable a microsimular


# Variables que no se tocan para microsimular.
# En caso de añadir una nueva el procesamiento posterior cambia

VARS_FIJAS =  ["estrato", "esc", "e6a", "edad", "sexo",
               "v13", "v13_propia", "v13_arrendada", "v13_cedida"]

# Esta es la variable que se modifica:

VARIABLE_A_MICROSIMULAR = "ypchtrabcor"

vars_a_cargar = VARS_FIJAS + [VARIABLE_A_MICROSIMULAR]

# Se acota la CASEN únicamente a las variables a utilizar
casen = casen_raw[vars_a_cargar].copy()


# Buena práctica: eliminar el df que ya no se usa, ergo ocupa espacio por las puras
del casen_raw



# Se obtiene la comuna de cada persona
casen["comuna"] = (casen["estrato"]//100).astype("Int64")
casen = casen.drop(columns = "estrato")

In [27]:
casen

,esc,e6a,edad,sexo,v13,v13_propia,v13_arrendada,v13_cedida,ypchtrabcor,comuna
0,12.0,11.0,54.0,2.0,1.0,2.0,NaN,NaN,520000.0,13111
1,12.0,11.0,28.0,2.0,1.0,2.0,NaN,NaN,520000.0,13111
2,17.0,13.0,27.0,2.0,1.0,2.0,NaN,NaN,520000.0,13111
3,10.0,11.0,19.0,2.0,1.0,2.0,NaN,NaN,520000.0,13111
4,12.0,11.0,56.0,1.0,1.0,2.0,NaN,NaN,520000.0,13111
...,...,...,...,...,...,...,...,...,...,...
38669,8.0,7.0,56.0,2.0,1.0,2.0,NaN,NaN,540787.0,13115
38670,12.0,11.0,33.0,1.0,3.0,NaN,NaN,8.0,209696.0,13115
38671,14.0,12.0,31.0,2.0,3.0,NaN,NaN,8.0,209696.0,13115
38672,NaN,7.0,10.0,1.0,3.0,NaN,NaN,8.0,209696.0,13115
38673,NaN,2.0,1.0,1.0,3.0,NaN,NaN,8.0,209696.0,13115

## Tabla de constraints por zona censal

In [36]:
# Para hacer calzar el censo con la casen

# nos estamos quedando con las cosas que nos interesan del censo, y además estamos renombrando columnas

ZONA_ID = "OBJECTID"


COLS_SEXO = {"hombre": "n_hombres", "mujer": "n_mujeres"}
COLS_EDAD = {
    "edad_0_5": "n_edad_0_5",
    "edad_6_13": "n_edad_6_13",
    "edad_14_17": "n_edad_14_17",
    "edad_18_24": "n_edad_18_24",
    "edad_25_44": "n_edad_25_44",
    "edad_45_59": "n_edad_45_59",
    "edad_60_mas": "n_edad_60_mas",
}

COLS_EDUC = ["educ_nunca", "educ_primaria", "educ_secundaria", "educ_terciaria"]
COLS_TENENCIA = {
    "ten_propia_pagada":"n_tenencia_propia_pagada",
    "ten_propia_pagadandose": "n_tenencia_propia_pagadandose",
    "ten_arrendada_contrato": "n_tenencia_arrendada_contrato",
    "ten_arrendada_sin_contrato": "n_tenencia_arrendada_sin_contrato",
    "ten_cedida_trabajo": "n_tenencia_cedida_trabajo",
    "ten_cedida_familiar": "n_tenencia_cedida_familiar",
    "ten_otro": "n_tenencia_otro",
}

constraints = censo_zonal[[ZONA_ID, "CUT", "COMUNA", "n_per", "n_hog"]].copy()

for nombre,col in{**COLS_SEXO, **COLS_EDAD}.items():
    constraints[nombre] = censo_zonal[col]


# Para educación tendremos 4 niveles
constraints["educ_nunca"] = censo_zonal["n_cine_nunca_curso_primera_infancia"]
constraints["educ_primaria"] = (censo_zonal["n_cine_primaria"] +
                                censo_zonal["n_cine_especial_diferencial"])

constraints["educ_secundaria"] = censo_zonal["n_cine_secundaria"]
constraints["educ_terciaria"] = censo_zonal["n_cine_terciaria_maestria_doctorado"]

In [37]:
constraints

,OBJECTID,CUT,COMUNA,n_per,n_hog,hombre,mujer,edad_0_5,edad_6_13,edad_14_17,edad_18_24,edad_25_44,edad_45_59,edad_60_mas,educ_nunca,educ_primaria,educ_secundaria,educ_terciaria
0,2702,13107,HUECHURABA,4776.0,1408.0,2294.0,2482.0,209.0,658.0,403.0,541.0,1198.0,1236.0,531.0,227.0,1192.0,955.0,2369.0
1,2703,13107,HUECHURABA,7091.0,1898.0,3386.0,3705.0,314.0,862.0,633.0,1024.0,1449.0,2068.0,741.0,366.0,1672.0,1605.0,3418.0
2,2704,13107,HUECHURABA,4991.0,1604.0,2364.0,2627.0,322.0,598.0,241.0,446.0,1639.0,898.0,847.0,366.0,1443.0,1556.0,1593.0
3,2705,13107,HUECHURABA,6898.0,2178.0,3321.0,3577.0,411.0,892.0,435.0,714.0,2088.0,1687.0,671.0,472.0,1451.0,1303.0,3648.0
4,2706,13107,HUECHURABA,5768.0,1912.0,2748.0,3020.0,348.0,670.0,329.0,604.0,1721.0,1264.0,832.0,417.0,1484.0,1389.0,2459.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1637,4487,13123,PROVIDENCIA,3491.0,1466.0,1539.0,1952.0,150.0,250.0,131.0,357.0,1084.0,653.0,866.0,179.0,500.0,872.0,1937.0
1638,4488,13123,PROVIDENCIA,1553.0,854.0,745.0,808.0,51.0,72.0,33.0,123.0,716.0,256.0,302.0,61.0,155.0,326.0,1010.0
1639,4526,13118,MACUL,3120.0,1088.0,1483.0,1637.0,127.0,293.0,154.0,300.0,846.0,596.0,804.0,161.0,1066.0,1029.0,857.0
1640,4902,13120,ÑUÑOA,2370.0,880.0,1097.0,1273.0,108.0,192.0,71.0,199.0,744.0,409.0,647.0,135.0,772.0,747.0,708.0
1641,4909,13120,ÑUÑOA,2935.0,1293.0,1326.0,1609.0,99.0,212.0,103.0,252.0,1133.0,473.0,663.0,128.0,530.0,782.0,1484.0